@file:Suppress("UNRESOLVED_REFERENCE", "ALL", "PACKAGE_OR_CLASSIFIER_REDECLARATION")

/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package app

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = AppClass()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
